# Generated by Django 5.0.6 on 2024-06-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
