# Generated by Django 5.0.6 on 2024-06-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="new_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
