version: "3.8"

services:
    web:
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./backend:/django
        ports:
            - "8000:8000"
        depends_on:
            - redis
        env_file:
            - ./backend/.env

    celery:
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: celery -A core worker --loglevel=info
        volumes:
            - ./backend:/django
        depends_on:
            - redis
        env_file:
            - ./backend/.env

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        stdin_open: true
        tty: true
